name: Build project
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Commit and push changes
        run: |
          git config --global user.name "abbytec"
          git config --global user.email "gpsmurfs@gmail.com"
      - run: |
          npm run build
          npm run deploy
