name: Build project
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: |
          npm i
          npm run build
      - name: Config an deploy git
        run: |
          git config --global user.name "abbytec"
          git config --global user.email "gpsmurfs@gmail.com"
          npm run deploy
